logging:
 file:
  name: ./logs/my-log.log
  logback:
    rollingpolicy:
      max-file-size: 20MB
      max-history: 30
pattern:
  console: '%yellow(%d{HH:mm:ss}) %green([%thread]) %highlight(%-5level) %boldMagenta(%logger{10}) - %cyan(%msg%n)'


