#family:
#  family-name: "happy"
#  father: ${father.name:zhangsan}
#  mother: "Rose"
#  child: "Tom"
#  age: ${random.int(1,30)}
#father:
#  name: "张三"


server:
  host: "localhost"
  port: 8080
  context-path: "/api"


person:
  first-name: ${first-name:Jhon}
  last-name: ${last-name:Doe}
  age: ${random.int(20,50)}
  id: ${random.uuid}
  phone: ${phone.number:1234567890}


student:
  name: 张小飞
  age: 20
  happy: true
  birth: 2004/10/14
  map: {k1: v1,k2: v2}
  list:
    - code
    - read
    - music
  dog:
    name: 虎子
    age: 11


db:
  url: jdbc:mysql://127.0.0.1:3306/spring_boot?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
  username: root
  password: password
  dirver-class-name: com.mysql.cj.jdbc.Driver



jwt:
  secret: helloworld
  expiration: 3600000 #单位毫秒



custom:
  qrcode:
    content: "http://www.baidu.com"
  log:
    level: "INFO"
  backup:
    location: D:\HuaweiMoveData\Users\keke666\Desktop\backup.log

spring:
  mail:
    host: smtp.qq.com
    username: 2319780642@qq.com
    password: ifcsoqvtevhydbei
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
  web:
    resources:
      static-locations:
  servlet:
     multipart:
      max-file-size: 10485760
      max-request-size: 10485760







